{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "budibase.fullname" . }}-proxy-pdb
  labels:
    {{- include "budibase.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: budibase-proxy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "budibase.fullname" . }}-apps-pdb
  labels:
    {{- include "budibase.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      io.kompose.service: app-service
---
{{- if .Values.services.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "budibase.fullname" . }}-worker-pdb
  labels:
    {{- include "budibase.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      io.kompose.service: worker-service
{{- end }}
{{- end }}
