controller:
  kind: DaemonSet
  admissionWebhooks:
    enabled: false

  service:
    type: NodePort
    nodePorts:
      tcp:
        9000: 30090
      udp:
        9001: 30091

tcp:
  9000: "default/test:8080"

udp:
  9001: "default/test:8080"
