controller:
  kind: DaemonSet
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
  tcp:
    configMapNamespace: default
  udp:
    configMapNamespace: default

tcp:
  9000: "default/test:8080"

udp:
  9001: "default/test:8080"
