name: deploy-featurebranch

on:
  pull_request:
    types: [
        labeled,
        # default types below (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
        opened,
        synchronize,
        reopened,
      ]

jobs:
  release:
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'Budibase/budibase') &&
      contains(github.event.pull_request.labels.*.name, 'feature-branch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_BRANCH: ${{ github.head_ref }}
          PAYLOAD_PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          repository: budibase/budibase-deploys
          event: featurebranch-qa-deploy
          github_pat: ${{ secrets.GH_ACCESS_TOKEN }}
