name: Budibase Prerelease
concurrency: release-prerelease

on: 
 push:
    branches:
      - develop
    paths:
      - '.aws/**'
      - '.github/**'
      - 'charts/**'
      - 'packages/**'
      - 'scripts/**'
      - 'package.json'
      - 'yarn.lock'
      - 'package.json'
      - 'yarn.lock'
 workflow_dispatch:

env:
  # Posthog token used by ui at build time
  # disable unless needed for testing
  # POSTHOG_TOKEN: phc_uDYOfnFt6wAbBAXkC6STjcrTpAFiWIhqgFcsC1UVO5F
  INTERCOM_TOKEN: ${{ secrets.INTERCOM_TOKEN }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  FEATURE_PREVIEW_URL: https://budirelease.live
      
jobs:
  release-images:
    runs-on: ubuntu-latest 

    steps:
      - name: Fail if branch is not develop
        if: github.ref != 'refs/heads/develop' 
        run: | 
          echo "Ref is not develop, you must run this job from develop."
          exit 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Pro
        run: yarn install:pro develop

      - run: yarn 
      - run: yarn bootstrap
      - run: yarn lint 
      - run: yarn build
      - run: yarn build:sdk
      - run: yarn test

      - name: Publish budibase packages to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: | 
          # setup the username and email.
          git config --global user.name "Budibase Staging Release Bot"
          git config --global user.email "<>"
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> .npmrc 
          yarn release:develop

      - name: Build/release Docker images
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          yarn build
          yarn build:docker:develop
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_API_KEY }}

  deploy-to-release-env:
    needs: [release-images]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get the current budibase release version
        id: version
        run: |
          release_version=$(cat lerna.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Pull values.yaml from budibase-infra
        run: | 
          curl -H "Authorization: token ${{ secrets.GH_PERSONAL_TOKEN }}" \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o values.release.yaml \
          -L https://api.github.com/repos/budibase/budibase-infra/contents/kubernetes/budibase-release/values.yaml
          wc -l values.release.yaml

      - name: Deploy to Release Environment
        uses: budibase/helm@v1.8.0
        with:
          release: budibase-release
          namespace: budibase
          chart: charts/budibase
          token: ${{ github.token }}
          helm: helm3
          values: |
            globals: 
              appVersion: develop
            ingress:
              enabled: true
              nginx: true
          value-files: >-
            [
              "values.release.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.RELEASE_KUBECONFIG }}'
      
      - name: Re roll app-service
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.RELEASE_KUBECONFIG_BASE64 }}
        with:
          args: rollout restart deployment app-service -n budibase

      - name: Re roll proxy-service
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.RELEASE_KUBECONFIG_BASE64 }}
        with:
          args: rollout restart deployment proxy-service -n budibase

      - name: Re roll worker-service
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.RELEASE_KUBECONFIG_BASE64 }}
        with:
          args: rollout restart deployment worker-service -n budibase

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.PROD_DEPLOY_WEBHOOK_URL }}
          content: "Release Env Deployment Complete: ${{ env.RELEASE_VERSION }} deployed to Budibase Release Env."
          embed-title: ${{ env.RELEASE_VERSION }}

  release-helm-chart:
    needs: [release-images]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Helm
        uses: azure/setup-helm@v1
        id: helm-install

      # due to helm repo index issue: https://github.com/helm/helm/issues/7363
      # we need to create new package in a different dir, merge the index and move the package back
      - name: Build and release helm chart
        run: |
          git config user.name "Budibase Helm Bot"
          git config user.email "<>"
          git reset --hard
          git pull
          mkdir sync
          echo "Packaging chart to sync dir"
          helm package charts/budibase --version 0.0.0-develop --app-version develop --destination sync
          echo "Packaging successful"
          git checkout gh-pages
          echo "Indexing helm repo"         
          helm repo index --merge docs/index.yaml sync
          mv -f sync/* docs
          rm -rf sync
          echo "Pushing new helm release"
          git add -A
          git commit -m "Helm Release: develop"
          git push

  trigger-deploy-to-qa-env:
    needs: [release-helm-chart]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the current budibase release version
        id: version
        run: |
          release_version=$(cat lerna.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV

      - uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          repository: budibase/budibase-deploys
          event: deploy-budibase-develop-to-qa
          github_pat: ${{ secrets.GH_ACCESS_TOKEN }}