name: Budibase Smoke Test

on:
 workflow_dispatch:
 schedule:
  - cron: "0 5 * * *" # every day at 5AM

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn bootstrap
      - run: yarn build
      - name: Pull cypress.env.yaml from budibase-infra
        run: | 
          curl -H "Authorization: token ${{ secrets.GH_PERSONAL_TOKEN }}" \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o packages/builder/cypress.env.json \
          -L https://api.github.com/repos/budibase/budibase-infra/contents/test/cypress.env.json
          wc -l packages/builder/cypress.env.json

      - name: Cypress run
        id: cypress
        continue-on-error: true
        uses: cypress-io/github-action@v2
        with:
          record: true
          install: false
          command: yarn test:e2e:ci:record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      # TODO: upload recordings to s3
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-west-1
        
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.BUDI_QA_WEBHOOK }}
          content: "Smoke test run completed with ${{ steps.cypress.outcome }}. See results at ${{ steps.cypress.outputs.dashboardUrl }}"
          embed-title: ${{ steps.cypress.outcome }}
          embed-color: ${{ steps.cypress.outcome == 'success' && '3066993' || '15548997' }}

