name: Budibase Nightly Tests

on:
 workflow_dispatch:
 schedule:
  - cron: "0 5 * * *" # every day at 5AM

jobs:
  nightly:
    runs-on: [self-hosted, qa]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: QA Core Integration Tests
        run: | 
          cd qa-core
          yarn
          yarn api:test:ci
        env:
          BUDIBASE_HOST: budicloud.qa.budibase.net
          BUDIBASE_ACCOUNTS_URL: https://account-portal.budicloud.qa.budibase.net